version: "3.1"

services:
 web:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks: 
      - webnet
 db:
    image: postgres:13
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass # Corrected the typo here
    volumes:
      - db-data:/var/lib/postgresql/data # Corrected the path and removed the 'type' property
    networks:
      - webnet
 adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - webnet

networks: 
 webnet:

volumes: 
 db-data:
